# Generated by Django 3.2.9 on 2021-12-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
