# Generated by Django 3.2.9 on 2021-12-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Link')),
                ('title', models.CharField(max_length=100, verbose_name='Qrupun adı')),
                ('linktype', models.CharField(max_length=100, verbose_name='Platforma')),
                ('image', models.FileField(upload_to='', verbose_name='Şəkil')),
                ('like', models.IntegerField(verbose_name='Like sayı')),
                ('views', models.IntegerField(verbose_name='Baxış sayı')),
                ('preminium', models.BooleanField(verbose_name='Preminium')),
                ('posting_date', models.DateTimeField(auto_now_add=True, verbose_name='Yüklənmə vaxtı')),
                ('updatedate', models.DateField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='Kategoriya')),
            ],
        ),
    ]
