# Generated by Django 3.2.9 on 2021-12-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Like sayı'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preminium',
            field=models.BooleanField(default=False, verbose_name='Preminium'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Baxış sayı'),
        ),
    ]
