# Generated by Django 3.2.9 on 2021-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211208_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updatedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
