# Generated by Django 3.2.9 on 2021-12-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Link'),
        ),
    ]
