# Generated by Django 3.2.9 on 2021-12-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='linktype',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook')], max_length=100, verbose_name='Platforma'),
        ),
    ]
