# Generated by Django 3.2.9 on 2021-12-17 15:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_linktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, size=[1280, 720], upload_to='', verbose_name='Sekil'),
        ),
    ]
